export enum Page {
  HOME = 'HOME',
  TRADITIONAL = 'TRADITIONAL',
  MODERN = 'MODERN',
  COMPARISON = 'COMPARISON',
  ABOUT_US = 'ABOUT_US',
  SUPPORT = 'SUPPORT',

  // Traditional Sub-pages
  AYURVEDA = 'AYURVEDA',
  HERBAL_MEDICINE = 'HERBAL_MEDICINE',
  TCM = 'TCM',
  NATUROPATHY = 'NATUROPATHY',
  UNANI = 'UNANI',
  FOLK_INDIGENOUS = 'FOLK_INDIGENOUS',

  // Modern Sub-pages
  ALLOPATHIC = 'ALLOPATHIC',
  PHARMACEUTICALS = 'PHARMACEUTICALS',
  SURGERY = 'SURGERY',
  DIAGNOSTIC = 'DIAGNOSTIC',
  PREVENTIVE = 'PREVENTIVE',
  BIOTECH = 'BIOTECH',

  // Case Study Sub-pages
  CASE_STUDY_INDIA = 'CASE_STUDY_INDIA',
  CASE_STUDY_CHINA = 'CASE_STUDY_CHINA',
  CASE_STUDY_AFRICA = 'CASE_STUDY_AFRICA',
  CASE_STUDY_BRAZIL = 'CASE_STUDY_BRAZIL',
  CASE_STUDY_JAPAN = 'CASE_STUDY_JAPAN',
}